# Generated by Django 5.2.6 on 2025-10-14 18:32

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[blog.validators.bad_keywords_validator]),
        ),
    ]
