name: continuous-integration
on: [push]
jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run manage.py test
